### ISSUE TITLE
build error after adding block

### ISSUE THREAD

**Issue by jeffpreussner** [ilyichv/shadcn-registry-template#2]
Hey, can you add a block example? I've added a couple blocks and I can build the registry fine but when I try to run the build script for the project it throws an error
```  Creating an optimized production build ...
 ✓ Compiled successfully
 ✓ Linting and checking validity of types    
 ✓ Collecting page data    
   Generating static pages (0/4)  [    ]Error: Functions cannot be passed directly to Client Components unless you explicitly expose it by marking it with "use server". Or maybe you meant to call this function rather than return it.
  {}
  ...
  ...
  ...```

**Comment by ilyichv** [comment]
There's probably an issue with the blocks that you made the error seems to be 
`Functions cannot be passed directly to Client Components unless you explicitly expose it by marking it with "use server". Or maybe you meant to call this function rather than return it.`

That's not an actual issue of the repo!

**Comment by jeffpreussner** [comment]
yes, the problem is with my block but thats why I asked for an example, the registry code from shadcn doesnt build for me.
